<?php
/*
*Template Name: cooler
*/
$home_url = esc_url(home_url());
$theme_url = get_template_directory_uri();
get_header();
?>

<div class="p-cooler">
    <div class="p-cooler_wrap">
        <h2>
            <label>◆◆◆</label>
            <p>ご希望の用途や広さを、下記の基準表の中から算定して下さい。</p>
            <label>◆◆◆</label>
        </h2>
        <h1>広さの目安(冷房時)</h1>
        <h3>あくまでも目安です。省エネには、1ランク上の馬力がおすすめです。</h3>

        <div class="p-cooler_wrap_table">
            <table class="p-cooler_wrap_table_wrap">
                <tbody class="p-cooler_wrap_table_wrap_tbody">
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <th class="p-cooler_wrap_table_wrap_tbody_tr_th">
                            <div class="p-cooler_wrap_table_wrap_tbody_tr_th_triangle">
                                <p>用途</p>
                                <p>馬力数</p>
                            </div>
                            <div class="p-cooler_wrap_table_wrap_tbody_tr_th_triangle2">
                                <p>馬力数</p>
                            </div>
                        </th>
                        <th class="p-cooler_wrap_table_wrap_tbody_tr_th">
                            <img src="<?php echo $theme_url ?>/images/cooler/restaurant.png">
                            <p>レストラン・食堂</p>
                        </th>
                        <th class="p-cooler_wrap_table_wrap_tbody_tr_th">
                            <img src="<?php echo $theme_url ?>/images/cooler/cafe.png">
                            <p>喫茶店・理容院</p>
                        </th>
                        <th class="p-cooler_wrap_table_wrap_tbody_tr_th">
                            <img src="<?php echo $theme_url ?>/images/cooler/shop.png">
                            <p>一般商店</p>
                        </th>
                        <th class="p-cooler_wrap_table_wrap_tbody_tr_th">
                            <img src="<?php echo $theme_url ?>/images/cooler/office.png">
                            <p>事務所</p>
                        </th>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                    <tr class="p-cooler_wrap_table_wrap_tbody_tr">
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                        <td>
                            <label>
                                <h3>40</h3>
                                <p>系</p>
                            </label>
                            <span>1.5馬力相当</span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="p-cooler_wrap_table_caution">
                <p>
                    古くなると能力ダウンで冷えなくなり、追加で買いたして結果的に高くついてしまうこともあります。<br>
                    ワンランクアップの省エネ運転がお薦めです。
                </p>
            </div>
        </div>

    </div>
</div>

<?php get_footer(); ?>